version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here

      - run:
          name: Send Email Notification
          command: |
            python -c '
            import smtplib
            from email.mime.text import MIMEText

            # Set your verified sender email address
            sender = "ahtesham.ahmad2018@gmail.com"
            # Set your recipient email address
            recipient = "altamashfaridi2023@gmail.com"
            # Set your SES SMTP server and port
            smtp_server = "email-smtp.ap-northeast-1.amazonaws.com"
            smtp_port = 587
            # Set your SES SMTP credentials
            smtp_username = "AKIAZ3KXKBVFXUWG4B4W"
            smtp_password = "BOuf3RZOFZUjV5S8b3E1a7RdmczwlPelpiHrmXqfRgc"

            # Email content
            subject = "CircleCI Build Notification"
            body = "Your CircleCI build has completed!"

            # Create a MIMEText object
            message = MIMEText(body)
            message['subject'] = subject
            message['From'] = sender
            message['To'] = recipient

            # Connect to the SMTP server and send the email
            try:
                server = smtplib.SMTP(smtp_server, smtp_port)
                server.starttls()
                server.login(smtp_username, smtp_password)
                server.sendmail(sender, recipient, message.as_string())
                server.quit()
            except Exception as e:
                print(f"Failed to send email: {e}")
            '