version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here
      - run:
          name: Check Notification status on success
          command: |
            python --version

  send_email_notification:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Send email notification
          command: |
            python EmailNotification_Fail.py

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build:
          on_success:
            - send_email_notification
          on_fail:
            - send_email_notification
