version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here

      - run:
          name: Send Email Notification
          command: |
            python EmailNotification.py
            
            
