version: 2.1
jobs:
  build1:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build1 here
      - run:
          name: Check Notification status on success (Build 1)
          command: |
            python --version

  build2:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build2 here
      - run:
          name: Check Notification status on success (Build 2)
          command: |
            python -version


  send_email_notification:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Send email notification
          command: |
              python EmailNotification_Fail.py

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build1:
          on_fail:
            - send_email_notification
      - build2:
          on_fail:
            - send_email_notification
      - send_email_notification:
          requires:
            - build1
            - build2
          filters:
            branches:
              ignore:
                - no-ci-notification
