version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      # Your build steps here

  notify_success:
    docker:
      - image: python:3.9
    steps:
      - run:
          name: Send success email
          command: |
            python EmailNotification_Success.py success "Build successful! :tada:"

  notify_failure:
    docker:
      - image: python:3.9
    steps:
      - run:
          name: Send failure email
          command: |
            python EmailNotification_Fail.py failure "Build failed! :x:"

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
    # Trigger the appropriate notification job based on success or failure
    # Adjust filters or conditions based on your needs (e.g., branches, tags, etc.)
    post-steps:
      - when:
          status: success
        run: notify_success
      - when:
          status: failure
        run: notify_failure
