version: 2.1
jobs:
  build1:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build1 here
      - run:
          name: Check Notification status on success (Build 1)
          command: |
            python --version

  build2:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build2 here
      - run:
          name: Check Notification status on success (Build 2)
          command: |
            python --version

  build3:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build3 here
      - run:
          name: Check Notification status on success (Build 3)
          command: |
            python --version

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build1
      - build2
      - build3

      - send_success_notification:
          requires:
            - build1
            - build2
            - build3
          filters:
            branches:
              ignore:
                - no-ci-notification
          on_success:
            - send_notification

      - send_failure_notification:
          requires:
            - build1
            - build2
            - build3
          filters:
            branches:
              ignore:
                - no-ci-notification
          on_fail:
            - send_notification

  send_notification:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Send custom email notification
          command: |
            python EmailNotification_Fail.py
