version: 2.1

jobs:
  build:
    docker:
      - image: node:14 # Choose the Node.js version you need
    steps:
      - checkout # Checkout the source code
      - run:
          name: Print the Hello World
          command: echo "Hello World"

  # Configure email notifications
notifications:
  email:
    recipients:
      - $NOTIFY_EMAILS
    branches:
      ignore: /.*/
        
workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
