version: 2.1
jobs:
  build1:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build1 here
      - run:
          name: Check Notification status on success (Build 1)
          command: |
            python --version

  build2:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build2 here
      - run:
          name: Check Notification status on success (Build 2)
          command: |
            python --version

  build3:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build3 here
      - run:
          name: Check Notification status on success (Build 3)
          command: |
            python --version

  send_build_status_notification:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Send overall status notification
          command: |
            if [ "$CIRCLE_WORKFLOW_STATUS" == "success" ]; then
              python EmailNotification_Success.py
            else
              python EmailNotification_Fail.py
            fi

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build1:
          on_success:
            - send_build_status_notification
          on_fail:
            - send_build_status_notification
      - build2:
          on_success:
            - send_build_status_notification
          on_fail:
            - send_build_status_notification
      - build3:
          on_success:
            - send_build_status_notification
          on_fail:
            - send_build_status_notification
