version: 2.1
jobs:
  build1:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here
      - run:
          name: Check Notification status on success
          command: |
            python --version
  build2:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here
      - run:
          name: Check Notification status on success
          command: |
            python -version       

workflows:
  version: 2
  build_and_notify:
    jobs:
    notify_success:
      jobs:
        - build
      when: on_success
      steps:
        - run:
            name: Send success notification
            command: |
              python EmailNotification_Success.py
    notify_failure:
      jobs:
        - build
      when: on_fail
      steps:
        - run:
            name: Send Failed notification
            command: |
              python EmailNotification_Fail.py
