version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Check Notification status on success
          command: |
            python --version

  notify_on_failure:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Send email notification for failure
          command: |
            python EmailNotification_Fail.py

  notify_on_success:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Send email notification for success
          command: |
            python EmailNotification_Success.py

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify_on_failure:
          requires:
            - build
          filters:
            status:
              - failed
      - notify_on_success:
          requires:
            - build
          filters:
            status:
              - success
