version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Install mailutils
          command: apt-get update && apt-get install -y mailutils

      # Your build steps go here

  notify_on_failure:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Install mailutils
          command: apt-get update && apt-get install -y mailutils

      - run:
          name: Send email notification on failure
          command: echo "Subject: Build Failed - $Custom_Email_Sample" | sendmail -v altamashfaridi@gmail.com

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify_on_failure:
          requires:
            - build
          filters:
            branches:
              only: main
