version: 2.1
jobs:
  build:
    # Your build configuration goes here
    # ...

  notify_on_failure:
    # This job will be triggered only when the build fails
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Send email notification on failure
          command: |
            echo "Subject: Build Failed - $Email_Sample" | sendmail -v altamashfaridi@gmail.com

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify_on_failure:
          requires:
            - build
          filters:
            branches:
              only: main
