version: 2.1
jobs:
  build1:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build1 here
      - run:
          name: Check Notification status on success (Build 1)
          command: |
            python --version
      - run:
          name: Send overall status notification (Build 1)
          command: |
            if [ "$CIRCLE_WORKFLOW_STATUS" != "success" ]; then
              python EmailNotification_Fail.py
            fi

  build2:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build2 here
      - run:
          name: Check Notification status on success (Build 2)
          command: |
            python --version
      - run:
          name: Send overall status notification (Build 2)
          command: |
            if [ "$CIRCLE_WORKFLOW_STATUS" != "success" ]; then
              python EmailNotification_Fail.py
            fi

  build3:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps for build3 here
      - run:
          name: Check Notification status on success (Build 3)
          command: |
            python --version
      - run:
          name: Send overall status notification (Build 3)
          command: |
            if [ "$CIRCLE_WORKFLOW_STATUS" != "success" ]; then
              python EmailNotification_Fail.py
            fi

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build1
      - build2
      - build3
