version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
    on_success:
      - run:
          name: Send success notification
          command: |
            python EmailNotification_Success.py

    # Send a notification if the entire workflow fails
    on_fail:
      - run:
          name: Send failure notification
          command: |
            python EmailNotification_Fail.py
            
            
