version: 2.1
jobs:
  send_email_notification:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Send email notification on failure
          command: |
            echo "Subject: Build Failed - $Email_Sample" | sendmail -v altamashfaridi@gmail.com

workflows:
  version: 2
  build-and-notify:
    jobs:
      - send_email_notification
