version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
           name: Checking command notification
           command: |
             python3 --version
             echo "Hi This is for testing"
      - run:
          name: Send failure email
          command: |
            python3 EmailNotification_Fail.py
          when: "on_fail"
      - run:
          name: Send success email
          command: |
            python3 EmailNotification_Success.py
          when: "on_success"
      # Your build steps here

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build       
