version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Your build steps here
      - run:
          name: Check Notification status on success
          command: |
            python EmailNotification_Success.py
          when: on_success
      - run:
          name: Check Notification status on failed
          command: |
            python EmailNotification_Fail.py
          when: on_fail

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
