version: 2.1
jobs:
  build_and_notify:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Run the first build
      - run:
          name: Run Build 1
          command: |
            # Your build steps for the first command (build) here
            echo "Build 1: Successful"
            # Set an environment variable to indicate success
            echo "BUILD1_STATUS=success" >> $BASH_ENV

      # Run the second build
      - run:
          name: Run Build 2
          command: |
            # Your build steps for the second command (build) here
            echo "Build 2: Failed"
            exit 1  # Simulate failure
            # Set an environment variable to indicate failure
            echo "BUILD2_STATUS=failure" >> $BASH_ENV

      # Send notification based on the overall build status
      - run:
          name: Send Notification
          command: |
            # Load the environment variables from the previous steps
            source $BASH_ENV
            # Check the status of each build
            if [ "$BUILD1_STATUS" == "success" ] && [ "$BUILD2_STATUS" == "success" ]; then
              echo "Sending overall success notification"
              # Replace this line with the actual command to send success notification
            else
              echo "Sending overall failure notification"
              # Replace this line with the actual command to send failure notification
            fi

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build_and_notify
