version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      # Your build steps here
      cd abc
      echo "Hi This is for testing"

  notify_success:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Send success email
          command: |
            python EmailNotification_Success.py

  notify_failure:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Send failure email
          command: |
            python EmailNotification_Fail.py

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify_success
          
