version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      # Your build steps here

  notify_success:
    docker:
      - image: python:3.9
    steps:
      - run:
          name: Send success email
          command: |
            python --version

  notify_failure:
    docker:
      - image: python:3.9
    steps:
      - run:
          name: Send failure email
          command: |
            python3 EmailNotification_Fail.py

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify_success
          
